clc; clear all;
ag = 0.03;
alphag = 0.08;
cs = 1.5;
etac = 0.5;
etad = 0.5;
am = 0.05;
alpham = 0.05;
Xmg = 5;
dmg = 0.21;
Xms = 10;
dms = 0.21;
Xcm = 50;
dms = 0.15;
Lgmmax = 200;
Lsmax = 100;
pmmax = 50;
Lr = 20; % kW
F = -50;
L_r = 50;
K = 10;
L_k_b = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100];
Lk_b = linspace(0, 200, 100);
pg = optimvar('pg', 'LowerBound', 0);
ps = optimvar('ps', 'LowerBound', 0);
U_g = pg; 
U_s = ps; 
prob_g = optimproblem('Objective', U_g, 'ObjectiveSense', 'maximize');
prob_s = optimproblem('Objective', U_s, 'ObjectiveSense', 'maximize');
sol_g = solve(prob_g);
sol_s = solve(prob_s);
p_g_opt = sol_g.pg;
p_s_opt = sol_s.ps;
L_m_g = optimvar('L_m_g', 'LowerBound', 0, 'UpperBound', Lgmmax);
L_m_s = optimvar('L_m_s', 'LowerBound', 0, 'UpperBound', Lsmax);
p_m = optimvar('p_m', 'LowerBound', 0, 'UpperBound', pmmax);
Um = p_m * (L_m_g + L_m_s);
cons1 = L_m_g + L_m_s == sum(L_k_b) - L_r;
cons2 = L_m_g + L_m_s >= 0;
prob_m = optimproblem('Objective', Um, 'ObjectiveSense', 'maximize');
prob_m.Constraints.cons1 = cons1;
prob_m.Constraints.cons2 = cons2;
sol_m = solve(prob_m);
pg = zeros(1, length(Lk_b));
ps = zeros(1, length(Lk_b));
pm = zeros(1, length(Lk_b));
for i = 1:length(Lk_b)
    Lkb = Lk_b(i);
    pg(i) = ag + alphag * Lkb;
    ps(i) = cs * (1 - etac) / (etad * etac) + etac * pg(i);
    pm(i) = am + alpham * (Lkb + Lr + F);
    if i==length(Lk_b);
       pg=pg*10;ps=ps*10;pm=pm*10;
    end
end
figure;
plot(Lk_b, pg, 'r', 'LineWidth', 2);
hold on;
plot(Lk_b, ps, 'g', 'LineWidth', 2);
plot(Lk_b, pm, 'b', 'LineWidth', 2);
xlabel('Basic Electricity Demand (Lk,b) [kW]');
ylabel('Optimal Electricity Prices');
title('Optimal Electricity Prices vs Basic Electricity Demands of Users');
legend('Utility Company (pg)', 'Energy Storage Company (ps)', 'Microgrid (pm)');
grid on;
